
/*
* HTML: <p id="console"></p><p id="result"></p>
* Using Jquery 3.3.1
*/

/*
* Instructions:
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


function calculate(limit) {
   var result = 0;
   var oneBefore = 1;
   var twoBefore = 0;
   
   while ((oneBefore + twoBefore) <= limit) {
   		
      // The current fibonacci value is the sum of the 2 last values
   	var fibonacciValue = oneBefore + twoBefore;
      
      twoBefore = oneBefore;
      oneBefore = fibonacciValue;
      
      $("#console").append(fibonacciValue + ",");
  		
      // sum only even-values
      if (fibonacciValue % 2 == 0) {
      	result += fibonacciValue;
      }      
   		
   }
   
   return result;
   
}

$("#result").text("Fibonacci sum: " + calculate(4000000));